# fly.toml app configuration for pricetracker
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pricetracker'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'
  NODE_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
